name: Publish workshop website

on:
  push:
    branches:
      - main
    paths:
      - "workshop/**"
      - ".github/workflows/publish-workshop-site.yml"

  workflow_dispatch:

permissions:
  contents: read
  packages: read
  pages: write
  id-token: write

concurrency:
  group: pages
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-24.04

    container:
      image: ghcr.io/drighelli/scid26_spe_sptr:latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Render workshop
        working-directory: workshop
        run: quarto render

      - name: Configure GitHub Pages
        uses: actions/configure-pages@v5

      - name: Upload website
        uses: actions/upload-pages-artifact@v4
        with:
          path: workshop/_site

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    runs-on: ubuntu-24.04
    needs: build

    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4